# Generated by Django 5.0.1 on 2024-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("Backend", "Backend"), ("Frontend", "Frontend")],
                default="backend",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
