# Generated by Django 5.0.1 on 2024-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(blank=True, to="api.question"),
        ),
    ]
