# Generated by Django 4.1.7 on 2023-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_country_profile_bio_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='developer', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='male', max_length=50),
        ),
    ]
